#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/rongyue/e5

# ---------------------------------------------------------------------------
# API level
#
# ro.board.first_api_level / ro.product.first_api_level are both 33 on the
# real device, so this is an Android 13 (LineageOS 20) launch device.
# ---------------------------------------------------------------------------
PRODUCT_SHIPPING_API_LEVEL := 33

# ---------------------------------------------------------------------------
# A/B + virtual A/B
#
# Partition list mirrors ro.product.ab_ota_partitions of the stock build, minus
# the Unisoc-only radios (nr_*, pm_sys, sml, teecfg, trustos, uboot, spl, ...)
# which are flashed with the vendor factory tool and are never touched by an
# Android OTA.
# ---------------------------------------------------------------------------
AB_OTA_UPDATER := true

AB_OTA_PARTITIONS += \
    boot \
    init_boot \
    dtbo \
    vendor_boot \
    system \
    system_ext \
    product \
    vendor \
    odm \
    vendor_dlkm \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor

$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/launch_with_vendor_ramdisk.mk)

PRODUCT_USE_DYNAMIC_PARTITIONS := true
PRODUCT_BUILD_SUPER_PARTITION := true

# ---------------------------------------------------------------------------
# Soong
# ---------------------------------------------------------------------------
PRODUCT_SOONG_NAMESPACES += $(DEVICE_PATH)

# ---------------------------------------------------------------------------
# HALs
#
# These are the AOSP implementations.  The stock vendor partition shipped
# Unisoc copies under the same module names; those were dropped from
# proprietary-files.txt, so the product has to build them here.
#
# Deliberately not listed, because this device keeps the vendor's own:
#   android.hardware.graphics.allocator@4.0-service  - no generic AOSP module
#     exists (only a Tensor-specific one), so the vendor blob is the only copy
#   android.hardware.gnss@2.1-service, android.hardware.thermal@2.0-service,
#   android.hardware.boot@1.2-service, ...           - served by vendor.sprd.*
# ---------------------------------------------------------------------------
PRODUCT_PACKAGES += \
    android.hardware.audio.service \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.camera.provider@2.4-service \
    android.hardware.drm-service.clearkey \
    android.hardware.gatekeeper@1.0-service.software \
    android.hardware.graphics.composer@2.4-service \
    android.hardware.health-service.example \
    android.hardware.power.stats-service.example \
    android.hardware.rebootescrow-service.default \
    android.hardware.security.keymint-service \
    android.hardware.sensors-service.multihal \
    android.hardware.usb-service.example \
    android.hardware.wifi@1.0-service

# Wi-Fi supplicant stack, from external/wpa_supplicant_8
PRODUCT_PACKAGES += \
    hostapd \
    wpa_supplicant

# ---------------------------------------------------------------------------
# First-stage mount
#
# The stock vendor_boot ramdisk ships first_stage_ramdisk/fstab.ums9158_1h10
# (extracted and inspected).  We ship our own copy instead of relying on the
# extracted vendor blob, because the stock file:
#   * lists system_dlkm, which this device tree does not build, and
#   * carries avb=vbmeta_* / avb_keys= constraints that make fs_mgr wait for
#     signed vbmeta images we do not have.
# ---------------------------------------------------------------------------
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/configs/fstab/fstab.ums9158_1h10:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.ums9158_1h10

# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
    ro.sf.lcd_density=150

# ---------------------------------------------------------------------------
# Vendor blobs
#
# Generated by ./extract-files.sh (see README.md); the repository lives at
# vendor/rongyue/e5 and is NOT part of this device tree.
# ---------------------------------------------------------------------------
$(call inherit-product, vendor/rongyue/e5/e5-vendor.mk)
