#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/rongyue/e5

# ---------------------------------------------------------------------------
# API level
#
# ro.board.first_api_level / ro.product.first_api_level are both 33 on the
# real device, so this is an Android 13 (LineageOS 20) launch device.
# ---------------------------------------------------------------------------
PRODUCT_SHIPPING_API_LEVEL := 33

# ---------------------------------------------------------------------------
# A/B + virtual A/B
#
# Partition list mirrors ro.product.ab_ota_partitions of the stock build, minus
# the Unisoc-only radios (nr_*, pm_sys, sml, teecfg, trustos, uboot, spl, ...)
# which are flashed with the vendor factory tool and are never touched by an
# Android OTA.
# ---------------------------------------------------------------------------
AB_OTA_UPDATER := true

AB_OTA_PARTITIONS += \
    boot \
    init_boot \
    dtbo \
    vendor_boot \
    system \
    system_ext \
    product \
    vendor \
    odm \
    vendor_dlkm \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor

$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/launch_with_vendor_ramdisk.mk)

PRODUCT_USE_DYNAMIC_PARTITIONS := true
PRODUCT_BUILD_SUPER_PARTITION := true

# ---------------------------------------------------------------------------
# Soong
# ---------------------------------------------------------------------------
PRODUCT_SOONG_NAMESPACES += $(DEVICE_PATH)

# ---------------------------------------------------------------------------
# First-stage mount
#
# The stock vendor_boot ramdisk ships first_stage_ramdisk/fstab.ums9158_1h10
# (extracted and inspected).  We ship our own copy instead of relying on the
# extracted vendor blob, because the stock file:
#   * lists system_dlkm, which this device tree does not build, and
#   * carries avb=vbmeta_* / avb_keys= constraints that make fs_mgr wait for
#     signed vbmeta images we do not have.
# ---------------------------------------------------------------------------
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/configs/fstab/fstab.ums9158_1h10:$(TARGET_COPY_OUT_VENDOR_RAMDISK)/first_stage_ramdisk/fstab.ums9158_1h10

# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
    ro.sf.lcd_density=150

# ---------------------------------------------------------------------------
# Vendor blobs
#
# Generated by ./extract-files.sh (see README.md); the repository lives at
# vendor/rongyue/e5 and is NOT part of this device tree.
# ---------------------------------------------------------------------------
$(call inherit-product, vendor/rongyue/e5/e5-vendor.mk)
